package org.jbookshelf.model.db.cayenne.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.jbookshelf.model.db.cayenne.Book;

/**
 * Class _Note was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Note extends CayenneDataObject {

    public static final String CHANGE_DATE_PROPERTY = "changeDate";
    public static final String CITATION_PROPERTY = "citation";
    public static final String CONTENT_PROPERTY = "content";
    public static final String PAGE_PROPERTY = "page";
    public static final String PAGE_COUNT_PROPERTY = "pageCount";
    public static final String POSITION_PROPERTY = "position";
    public static final String TITLE_PROPERTY = "title";
    public static final String BOOK_PROPERTY = "book";

    public static final String ID_PK_COLUMN = "ID";

    public void setChangeDate(Date changeDate) {
        writeProperty("changeDate", changeDate);
    }
    public Date getChangeDate() {
        return (Date)readProperty("changeDate");
    }

    public void setCitation(String citation) {
        writeProperty("citation", citation);
    }
    public String getCitation() {
        return (String)readProperty("citation");
    }

    public void setContent(String content) {
        writeProperty("content", content);
    }
    public String getContent() {
        return (String)readProperty("content");
    }

    public void setPage(Integer page) {
        writeProperty("page", page);
    }
    public Integer getPage() {
        return (Integer)readProperty("page");
    }

    public void setPageCount(Integer pageCount) {
        writeProperty("pageCount", pageCount);
    }
    public Integer getPageCount() {
        return (Integer)readProperty("pageCount");
    }

    public void setPosition(Float position) {
        writeProperty("position", position);
    }
    public Float getPosition() {
        return (Float)readProperty("position");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setBook(Book book) {
        setToOneTarget("book", book, true);
    }

    public Book getBook() {
        return (Book)readProperty("book");
    }


}
