package org.jbookshelf.model.db.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.jbookshelf.model.db.cayenne.Book;

/**
 * Class _PhysicalBook was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PhysicalBook extends CayenneDataObject {

    public static final String CHARSET_NAME_PROPERTY = "charsetName";
    public static final String FILE_NAME_PROPERTY = "fileName";
    public static final String UNPACKED_FILE_NAME_PROPERTY = "unpackedFileName";
    public static final String VIEWER_PROPERTY = "viewer";
    public static final String BOOK_PROPERTY = "book";

    public static final String ID_PK_COLUMN = "ID";

    public void setCharsetName(String charsetName) {
        writeProperty("charsetName", charsetName);
    }
    public String getCharsetName() {
        return (String)readProperty("charsetName");
    }

    public void setFileName(String fileName) {
        writeProperty("fileName", fileName);
    }
    public String getFileName() {
        return (String)readProperty("fileName");
    }

    public void setUnpackedFileName(String unpackedFileName) {
        writeProperty("unpackedFileName", unpackedFileName);
    }
    public String getUnpackedFileName() {
        return (String)readProperty("unpackedFileName");
    }

    public void setViewer(String viewer) {
        writeProperty("viewer", viewer);
    }
    public String getViewer() {
        return (String)readProperty("viewer");
    }

    public void setBook(Book book) {
        setToOneTarget("book", book, true);
    }

    public Book getBook() {
        return (Book)readProperty("book");
    }


}
