<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jbookshelf"
    nsURI="http:///org/jbookshelf.ecore" nsPrefix="org.jbookshelf">
  <eClassifiers xsi:type="ecore:EClass" name="Author" eSuperTypes="#//Categorizable platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="readingUnits" upperBound="-1"
        eType="#//ReadingUnit" eOpposite="#//ReadingUnit/authors"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadingUnit" eSuperTypes="#//Categorizable platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authors" upperBound="-1"
        eType="#//Author" eOpposite="#//Author/readingUnits"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="physical" lowerBound="1"
        eType="#//PhysicalUnit" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="read" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category" eSuperTypes="#//Commentable platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizables" upperBound="-1"
        eType="#//Categorizable" eOpposite="#//Categorizable/categories"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" eType="#//Commentable"
        eOpposite="#//Commentable/comments"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commentable" abstract="true" eSuperTypes="#//Unique platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eOperations name="queryComments" upperBound="-1" eType="#//Comment">
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" containment="true" resolveProxies="false" eOpposite="#//Comment/subject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Categorizable" abstract="true" eSuperTypes="#//Commentable platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//Category" eOpposite="#//Category/categorizables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unique" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="related" upperBound="-1"
        eType="#//Unique" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookShelf">
    <eOperations name="addAuthor" eType="#//Author">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addCategory" eType="#//Category">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addReadingUnit" eType="#//ReadingUnit">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="author" eType="#//Author"/>
      <eParameters name="category" eType="#//Category"/>
      <eParameters name="physicalUnit" eType="#//PhysicalUnit"/>
    </eOperations>
    <eOperations name="queryAuthors" upperBound="-1" eType="#//Author">
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="queryCategories" upperBound="-1" eType="#//Category">
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="queryUniques" upperBound="-1" eType="#//Unique">
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="queryUnits" upperBound="-1" eType="#//ReadingUnit">
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="isRead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eOperations name="removeUnique">
      <eParameters name="unique" eType="#//Unique"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authors" upperBound="-1"
        eType="#//Author" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//Category" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readingUnits" upperBound="-1"
        eType="#//ReadingUnit" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchiveFile" eSuperTypes="#//PhysicalUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="archiveFile" eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexFileFolder" eSuperTypes="#//PhysicalUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexFile" eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexFolder" eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalUnit" abstract="true">
    <eOperations name="openUnit"/>
    <eOperations name="openFolder"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleFile" eSuperTypes="#//PhysicalUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleFileFolder" eSuperTypes="#//PhysicalUnit">
    <eOperations name="openFolder"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="folder" eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="singleFile" eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
</ecore:EPackage>
