<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jbookshelf"
    nsURI="http:///org/jbookshelf.ecore" nsPrefix="org.jbookshelf">
  <eClassifiers xsi:type="ecore:EClass" name="Author" eSuperTypes="#//Unique #//Commentable #//Categorizable platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="readingUnits" upperBound="-1"
        eType="#//ReadingUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReadingUnit" eSuperTypes="#//Unique #//Commentable #//Categorizable platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="authors" upperBound="-1"
        eType="#//Author"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="physical" lowerBound="1"
        eType="#//PhysicalUnit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRead" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Category" eSuperTypes="#//Unique platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categorizables" upperBound="-1"
        eType="#//Categorizable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="creationDate" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subject" eType="#//Commentable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commentable">
    <eOperations name="queryComments" upperBound="-1" eType="#//Comment">
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Categorizable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//Category"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unique">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="related" upperBound="-1"
        eType="#//Unique"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookShelf">
    <eOperations name="addAuthor" eType="#//Author">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addCategory" eType="#//Category">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addReadingUnit" eType="#//ReadingUnit">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="author" eType="#//Author"/>
      <eParameters name="category" eType="#//Category"/>
      <eParameters name="physicalUnit" eType="#//PhysicalUnit"/>
    </eOperations>
    <eOperations name="queryAuthors" upperBound="-1" eType="#//Author">
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="queryCategories" upperBound="-1" eType="#//Category">
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="queryUniques" upperBound="-1" eType="#//Unique">
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="queryUnits" upperBound="-1" eType="#//ReadingUnit">
      <eParameters name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eParameters name="isRead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uniques" upperBound="-1"
        eType="#//Unique" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="authors" upperBound="-1"
        eType="#//Author" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//Category" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="readingUnits" upperBound="-1"
        eType="#//ReadingUnit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storage" lowerBound="1"
        eType="#//BookShelfStorage" containment="true" eOpposite="#//BookShelfStorage/bookShelf"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArchiveFile" eSuperTypes="#//PhysicalUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="archiveFile" lowerBound="1"
        eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexFileFolder" eSuperTypes="#//PhysicalUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexFile" lowerBound="1"
        eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexFolder" lowerBound="1"
        eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalUnit">
    <eOperations name="openUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleFile" eSuperTypes="#//PhysicalUnit">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" lowerBound="1" eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleFileFolder" eSuperTypes="#//PhysicalUnit">
    <eOperations name="openFolder"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="folder" lowerBound="1"
        eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="singleFile" lowerBound="1"
        eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BookShelfStorage">
    <eOperations name="loadCollection"/>
    <eOperations name="saveCollection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bookShelf" lowerBound="1"
        eType="#//BookShelf" eOpposite="#//BookShelf/storage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleFileStorage" eSuperTypes="#//BookShelfStorage">
    <eOperations name="backupCollection">
      <eParameters name="externalFile" eType="#//File"/>
    </eOperations>
    <eOperations name="restoreCollection">
      <eParameters name="externalFile" eType="#//File"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionStorageFile"
        lowerBound="1" eType="#//File"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
</ecore:EPackage>
