
    create table Author (
        id bigint not null,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table Author_Book (
        authors_id bigint not null,
        books_id bigint not null,
        primary key (authors_id, books_id)
    );

    create table Book (
        id bigint not null,
        name varchar(255) not null,
        lastread_id bigint,
        primary key (id)
    );

    create table Category (
        id bigint not null,
        name varchar(255) not null,
        parent_id bigint,
        primary key (id)
    );

    create table Category_Book (
        categories_id bigint not null,
        books_id bigint not null,
        primary key (categories_id, books_id)
    );

    create table Note (
        id bigint generated by default as identity,
        changeDate timestamp not null,
        citation varchar(32767),
        content varchar(32767),
        page integer,
        pageCount integer,
        position float,
        title varchar(255) not null,
        BOOK_ID bigint not null,
        primary key (id)
    );

    create table PHYSICAL_BOOK (
        id bigint generated by default as identity,
        charsetName varchar(255),
        fileName varchar(255) not null,
        unpackedFileName varchar(255),
        viewer varchar(255),
        book_id bigint not null,
        primary key (id),
        unique (book_id)
    );

    create table RELATED_BOOKS (
        Book_id bigint not null,
        relatedBooks_id bigint not null,
        primary key (Book_id, relatedBooks_id)
    );

    create index author_name_ind on Author (name);

    alter table Author_Book 
        add constraint FK_BOOK_AUTHOR 
        foreign key (authors_id) 
        references Author;

    alter table Author_Book 
        add constraint FK_AUTHOR_BOOK 
        foreign key (books_id) 
        references Book;

    create index book_name_ind on Book (name);

    alter table Book 
        add constraint FK_LASTREAD_BOOK 
        foreign key (lastread_id) 
        references Note;

    create index category_name_ind on Category (name);

    alter table Category 
        add constraint FK_PARENT_CATEGORY 
        foreign key (parent_id) 
        references Category;

    alter table Category_Book 
        add constraint FK_BOOK_CATEGORY 
        foreign key (categories_id) 
        references Category;

    alter table Category_Book 
        add constraint FK_CATEGORY_BOOK 
        foreign key (books_id) 
        references Book;

    alter table Note 
        add constraint FK_NOTE_BOOK 
        foreign key (BOOK_ID) 
        references Book;

    alter table PHYSICAL_BOOK 
        add constraint FK_PHYSICAL_BOOK 
        foreign key (book_id) 
        references Book;

    alter table RELATED_BOOKS 
        add constraint FK_MAIN_BOOK 
        foreign key (Book_id) 
        references Book;

    alter table RELATED_BOOKS 
        add constraint FK_RELATED_BOOK 
        foreign key (relatedBooks_id) 
        references Book;

    create sequence hibernate_sequence;
