
    alter table Note 
        drop constraint FK_BOOK_ID;

    drop table Book if exists;

    drop table Note if exists;

    create table Book (
        id bigint generated by default as identity (start with 1),
        changeDate timestamp not null,
        name varchar(255) not null,
        read float not null,
        primary key (id),
        unique (name)
    );

    create table Note (
        id bigint generated by default as identity (start with 1),
        changeDate timestamp not null,
        content varchar(2147483647) not null,
        title varchar(255) not null,
        BOOK_ID bigint not null,
        primary key (id)
    );

    alter table Note 
        add constraint FK_BOOK_ID 
        foreign key (BOOK_ID) 
        references Book;
