/*
 * BookAdditionDialog.java Created on 1 Ноябрь 2008 г., 16:35
 */

package org.jbookshelf.gui;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import org.jbookshelf.Author;
import org.jbookshelf.Category;
import org.jbookshelf.PhysicalUnit;
import org.jbookshelf.Unique;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.jdesktop.swingx.autocomplete.ObjectToStringConverter;
import org.util.FileImporter;
import org.util.storage.Storage;

/**
 * @author uik
 */
public class BookAdditionDialog
    extends javax.swing.JDialog
{
    private ObjectToStringConverter converter = new ObjectToStringConverter()
                                              {
                                                  @Override
                                                  public String getPreferredStringForItem(
                                                      Object object )
                                                  {
                                                      if ( object == null )
                                                      {
                                                          return null;
                                                      }

                                                      if ( object instanceof Unique )
                                                      {
                                                          return ((Unique) object).getName();
                                                      }

                                                      return object.toString();
                                                  }
                                              };

    /** Creates new form BookAdditionDialog */
    public BookAdditionDialog(
        java.awt.Frame parent,
        boolean modal )
    {
        super( parent, modal );
        initComponents();

        initCustomComponents();

        registerComponents();
    }

    private void registerComponents()
    {
        components.add( bookTextField );
        components.add( authorTextField );
        components.add( categoryTextField );
        components.add( fileTextField );
    }

    private void initCustomComponents()
    {
        AutoCompleteDecorator.decorate( authorTextField, Storage.getBookShelf().getAuthors(), false, converter );
        AutoCompleteDecorator.decorate( categoryTextField, Storage.getBookShelf().getCategories(), false, converter );
        // todo better autocomplete
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        authorTextField = new javax.swing.JTextField();
        bookTextField = new javax.swing.JTextField();
        isReadCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        chooseButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addNContinueButton = new javax.swing.JButton();
        addNCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation( javax.swing.WindowConstants.DISPOSE_ON_CLOSE );

        jLabel1.setFont( new java.awt.Font( "Tahoma", 1, 14 ) );
        jLabel1.setText( "Add book to Collection" );

        jLabel3.setText( "Name" );

        jLabel4.setText( "Author *" );

        jLabel5.setText( "Category *" );

        categoryTextField.setText( "jTextField1" );

        authorTextField.setText( "jTextField2" );

        bookTextField.setText( "jTextField3" );

        isReadCheckBox.setText( "Already read" );
        isReadCheckBox.setHorizontalTextPosition( javax.swing.SwingConstants.LEADING );

        jLabel2.setText( "File" );

        fileTextField.setText( "jTextField4" );

        chooseButton.setText( "Choose..." );
        chooseButton.addActionListener( new java.awt.event.ActionListener()
        {
            @SuppressWarnings( "synthetic-access" )
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                chooseButtonActionPerformed( evt );
            }
        } );

        cancelButton.setText( "Cancel" );
        cancelButton.addActionListener( new java.awt.event.ActionListener()
        {
            @SuppressWarnings( "synthetic-access" )
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                cancelButtonActionPerformed( evt );
            }
        } );

        addNContinueButton.setText( "Add And Continue" );
        addNContinueButton.addActionListener( new java.awt.event.ActionListener()
        {
            @SuppressWarnings( "synthetic-access" )
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                addNContinueButtonActionPerformed( evt );
            }
        } );

        addNCloseButton.setText( "Add And Close" );
        addNCloseButton.addActionListener( new java.awt.event.ActionListener()
        {
            @SuppressWarnings( "synthetic-access" )
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                addNCloseButtonActionPerformed( evt );
            }
        } );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
        getContentPane().setLayout( layout );
        layout.setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup().addComponent( jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300,
                Short.MAX_VALUE ).addGap( 150, 150, 150 ) ).addComponent( jSeparator1,
            javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE ).addGroup(
            layout.createSequentialGroup().addContainerGap().addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addComponent( isReadCheckBox )
                    .addGroup(
                        layout.createSequentialGroup().addGroup(
                            layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addComponent(
                                jLabel5 ).addComponent( jLabel4 ).addComponent( jLabel3 ).addComponent( jLabel2 ) )
                            .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
                                    javax.swing.GroupLayout.Alignment.TRAILING,
                                    layout.createSequentialGroup().addComponent( fileTextField,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE ).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                        .addComponent( chooseButton ) ).addComponent( authorTextField,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE ).addComponent(
                                    bookTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE )
                                    .addComponent( categoryTextField, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE ) ) ) )
                .addContainerGap() ).addGroup(
            javax.swing.GroupLayout.Alignment.TRAILING,
            layout.createSequentialGroup().addContainerGap( 51, Short.MAX_VALUE ).addComponent( addNCloseButton )
                .addGap( 18, 18, 18 ).addComponent( addNContinueButton ).addGap( 18, 18, 18 ).addComponent(
                    cancelButton ).addContainerGap() ) );
        layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup().addComponent( jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                javax.swing.GroupLayout.PREFERRED_SIZE ).addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( jSeparator1,
                javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE ).addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel3 )
                    .addComponent( bookTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18,
                18, 18 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel4 )
                    .addComponent( authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18,
                18, 18 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel5 )
                    .addComponent( categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18,
                18, 18 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel2 )
                    .addComponent( chooseButton ).addComponent( fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING ).addGroup(
                    layout.createSequentialGroup().addGap( 18, 18, 18 ).addComponent( isReadCheckBox ).addContainerGap(
                        47, Short.MAX_VALUE ) ).addGroup(
                    layout.createSequentialGroup().addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                        .addGroup(
                            layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent(
                                cancelButton ).addComponent( addNContinueButton ).addComponent( addNCloseButton ) )
                        .addContainerGap() ) ) ) );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chooseButtonActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_chooseButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        if ( fileChooser.showOpenDialog( this ) == JFileChooser.APPROVE_OPTION )
        {
            fileTextField.setText( fileChooser.getSelectedFile().getAbsolutePath() );
        }
    }// GEN-LAST:event_chooseButtonActionPerformed

    private void cancelButtonActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }// GEN-LAST:event_cancelButtonActionPerformed

    private void addNContinueButtonActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_addNContinueButtonActionPerformed
        if ( addBook() )
        {
            clear();
        }
    }// GEN-LAST:event_addNContinueButtonActionPerformed

    private void addNCloseButtonActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_addNCloseButtonActionPerformed
        if ( addBook() )
        {
            dispose();
        }
    }// GEN-LAST:event_addNCloseButtonActionPerformed

    private boolean addBook()
    {
        String bookName = bookTextField.getText();
        if ( bookName.equals( "" ) )
        {
            JOptionPane.showMessageDialog( this, "Book name not specified", "Error", JOptionPane.ERROR_MESSAGE );
            return false;
        }

        File file = new File( fileTextField.getText() );
        if ( !file.exists() )
        {
            JOptionPane
                .showMessageDialog( this, file.getName() + " does not exist", "Error", JOptionPane.ERROR_MESSAGE );
            return false;
        }

        String authorName = authorTextField.getText();
        Author author = Storage.getBookShelf().addAuthor( authorName );

        String categoryName = categoryTextField.getText();
        Category category = Storage.getBookShelf().addCategory( categoryName );

        PhysicalUnit physicalUnit = FileImporter.createPhysicalUnit( file );
        Storage.getBookShelf().addReadingUnit( bookName, author, category, physicalUnit );

        CollectionPanel.getInstance().updateTree();

        JOptionPane.showMessageDialog( this, bookName + " added" );
        return true;
    }

    private void clear()
    {
        for ( JComponent component : components )
        {
            if ( component instanceof JTextField )
            {
                ((JTextField) component).setText( "" );
            }
        }
        isReadCheckBox.setText( "false" );
    }

    private List<JComponent> components = new ArrayList<JComponent>();

    /**
     * @param args the command line arguments
     */
    public static void main(
        String args[] )
    {
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            @Override
            public void run()
            {
                BookAdditionDialog dialog = new BookAdditionDialog( new javax.swing.JFrame(), true );
                dialog.addWindowListener( new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(
                        java.awt.event.WindowEvent e )
                    {
                        System.exit( 0 );
                    }
                } );
                dialog.setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton    addNCloseButton;
    private javax.swing.JButton    addNContinueButton;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JTextField bookTextField;
    private javax.swing.JButton    cancelButton;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JButton    chooseButton;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JCheckBox  isReadCheckBox;
    private javax.swing.JLabel     jLabel1;
    private javax.swing.JLabel     jLabel2;
    private javax.swing.JLabel     jLabel3;
    private javax.swing.JLabel     jLabel4;
    private javax.swing.JLabel     jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
