/*
 * BookAdditionDialog.java Created on 1 Ноябрь 2008 г., 16:35
 */

package org.jbookshelf.gui;

/**
 * @author uik
 */
public class BookAdditionDialog
    extends javax.swing.JDialog
{

    /** Creates new form BookAdditionDialog */
    public BookAdditionDialog(
        java.awt.Frame parent,
        boolean modal )
    {
        super( parent, modal );
        initComponents();
        initCustomComponents();
    }

    private void initCustomComponents()
    {
        // TODO Auto-generated method stub
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        categoryTextField = new javax.swing.JTextField();
        authorTextField = new javax.swing.JTextField();
        bookTextField = new javax.swing.JTextField();
        isReadCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        fileTextField = new javax.swing.JTextField();
        chooseButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        addNContinueButton = new javax.swing.JButton();
        addNCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation( javax.swing.WindowConstants.DISPOSE_ON_CLOSE );

        jLabel1.setFont( new java.awt.Font( "Tahoma", 1, 14 ) );
        jLabel1.setText( "Add book to Collection" );

        jLabel3.setText( "Name" );

        jLabel4.setText( "Author *" );

        jLabel5.setText( "Category *" );

        categoryTextField.setText( "jTextField1" );

        authorTextField.setText( "jTextField2" );

        bookTextField.setText( "jTextField3" );

        isReadCheckBox.setText( "Already read" );
        isReadCheckBox.setHorizontalTextPosition( javax.swing.SwingConstants.LEADING );

        jLabel2.setText( "File" );

        fileTextField.setText( "jTextField4" );

        chooseButton.setText( "Choose..." );

        cancelButton.setText( "Cancel" );

        addNContinueButton.setText( "Add And Continue" );

        addNCloseButton.setText( "Add And Close" );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
        getContentPane().setLayout( layout );
        layout.setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup().addComponent( jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300,
                Short.MAX_VALUE ).addGap( 150, 150, 150 ) ).addComponent( jSeparator1,
            javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE ).addGroup(
            layout.createSequentialGroup().addContainerGap().addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addComponent( isReadCheckBox )
                    .addGroup(
                        layout.createSequentialGroup().addGroup(
                            layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addComponent(
                                jLabel5 ).addComponent( jLabel4 ).addComponent( jLabel3 ).addComponent( jLabel2 ) )
                            .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
                                    javax.swing.GroupLayout.Alignment.TRAILING,
                                    layout.createSequentialGroup().addComponent( fileTextField,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE ).addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                                        .addComponent( chooseButton ) ).addComponent( authorTextField,
                                    javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE ).addComponent(
                                    bookTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE )
                                    .addComponent( categoryTextField, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE ) ) ) )
                .addContainerGap() ).addGroup(
            javax.swing.GroupLayout.Alignment.TRAILING,
            layout.createSequentialGroup().addContainerGap( 51, Short.MAX_VALUE ).addComponent( addNCloseButton )
                .addGap( 18, 18, 18 ).addComponent( addNContinueButton ).addGap( 18, 18, 18 ).addComponent(
                    cancelButton ).addContainerGap() ) );
        layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup().addComponent( jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27,
                javax.swing.GroupLayout.PREFERRED_SIZE ).addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( jSeparator1,
                javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE ).addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel3 )
                    .addComponent( bookTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18,
                18, 18 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel4 )
                    .addComponent( authorTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18,
                18, 18 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel5 )
                    .addComponent( categoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18,
                18, 18 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel2 )
                    .addComponent( chooseButton ).addComponent( fileTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING ).addGroup(
                    layout.createSequentialGroup().addGap( 18, 18, 18 ).addComponent( isReadCheckBox ).addContainerGap(
                        47, Short.MAX_VALUE ) ).addGroup(
                    layout.createSequentialGroup().addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                        .addGroup(
                            layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent(
                                cancelButton ).addComponent( addNContinueButton ).addComponent( addNCloseButton ) )
                        .addContainerGap() ) ) ) );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(
        String args[] )
    {
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            @Override
            public void run()
            {
                BookAdditionDialog dialog = new BookAdditionDialog( new javax.swing.JFrame(), true );
                dialog.addWindowListener( new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(
                        java.awt.event.WindowEvent e )
                    {
                        System.exit( 0 );
                    }
                } );
                dialog.setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton    addNCloseButton;
    private javax.swing.JButton    addNContinueButton;
    private javax.swing.JTextField authorTextField;
    private javax.swing.JTextField bookTextField;
    private javax.swing.JButton    cancelButton;
    private javax.swing.JTextField categoryTextField;
    private javax.swing.JButton    chooseButton;
    private javax.swing.JTextField fileTextField;
    private javax.swing.JCheckBox  isReadCheckBox;
    private javax.swing.JLabel     jLabel1;
    private javax.swing.JLabel     jLabel2;
    private javax.swing.JLabel     jLabel3;
    private javax.swing.JLabel     jLabel4;
    private javax.swing.JLabel     jLabel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
