/*
 * MainWindow.java Created on 15 Ноябрь 2008 г., 12:41
 */

package org.jbookshelf.gui;

import java.awt.BorderLayout;

import javax.swing.JSplitPane;

import org.jbookshelf.BookShelf;
import org.jbookshelf.JbookshelfFactory;
import org.jbookshelf.SingleFileStorage;
import org.util.settings.Settings;

/**
 * @author eav
 */
public class MainWindow
    extends javax.swing.JFrame
{
    private ToolBar         toolBar         = new ToolBar();
    private JSplitPane      splitPane       = new JSplitPane();
    private CollectionPanel collectionPanel = new CollectionPanel();
    private RelatedPanel    relatedPanel    = new RelatedPanel();

    private BookShelf       bookShelf       = JbookshelfFactory.eINSTANCE.createBookShelf();

    private Settings        settings        = Settings.getInstance();

    /** Creates new form MainWindow */
    public MainWindow()
    {
        initCustomComponents();
        initComponents();

        initModel();
    }

    private void initModel()
    {
        SingleFileStorage bookShelfStorage = JbookshelfFactory.eINSTANCE.createSingleFileStorage();
        bookShelf.setStorage( bookShelfStorage );
        bookShelfStorage.setBookShelf( bookShelf );
        bookShelfStorage.setCollectionStorageFile( settings.getCollectionFile() );
        bookShelfStorage.loadCollection();

        collectionPanel.setCollection( bookShelf );
    }

    private void initCustomComponents()
    {
        add( toolBar, BorderLayout.NORTH );
        add( splitPane, BorderLayout.SOUTH );
        splitPane.setLeftComponent( collectionPanel );
        splitPane.setRightComponent( relatedPanel );
        splitPane.setResizeWeight( 0.7 );
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        setDefaultCloseOperation( javax.swing.WindowConstants.EXIT_ON_CLOSE );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(
        String args[] )
    {
        java.awt.EventQueue.invokeLater( new Runnable()
        {
            public void run()
            {
                new MainWindow().setVisible( true );
            }
        } );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
