/*
 * SettingsDialog.java Created on 31 Октябрь 2008 г., 22:43
 */
package org.jbookshelf.gui;

import java.awt.Component;
import java.awt.Window;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;

import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

import org.util.settings.JBookShelfSettings;
import org.util.settings.Settings;

/**
 * @author eav
 */
public class SettingsDialog
    extends javax.swing.JDialog
    implements
        JBookShelfSettings
{
    private Settings settings = Settings.getInstance();

    /** Creates new form SettingsDialog */
    public SettingsDialog(
        java.awt.Frame parent,
        boolean modal )
    {
        super( parent, modal );
        initComponents();

        registerComponents();

        arrangeSettingValues();

        fileChooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY );
    }

    private void arrangeSettingValues()
    {
        langComboBox.setSelectedItem( settings.getProperty( LANGUAGE ) );
        langComboBoxActionPerformed( null );
        lafComboBox.setSelectedItem( settings.getProperty( LAF ) );
        lafComboBoxActionPerformed( null );
        tmpTextField.setText( settings.getProperty( TEMP_FOLDER ) );
        jbsTextField.setText( settings.getProperty( JBS_FOLDER ) );
        importTextField.setText( settings.getProperty( IMPORT_MASK ) );
    }

    private void readSettingValues()
    {
        settings.setProperty( LANGUAGE, langComboBox.getSelectedItem().toString() );
        settings.setProperty( LAF, lafComboBox.getSelectedItem().toString() );
        settings.setProperty( TEMP_FOLDER, tmpTextField.getText() );
        settings.setProperty( JBS_FOLDER, jbsTextField.getText() );
        settings.setProperty( IMPORT_MASK, importTextField.getText() );
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        restoreButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        importTextField = new javax.swing.JTextField();
        jbsTextField = new javax.swing.JTextField();
        chooseJBSFolderButton = new javax.swing.JButton();
        tmpTextField = new javax.swing.JTextField();
        chooseTempFolderButton = new javax.swing.JButton();
        lafComboBox = new javax.swing.JComboBox();
        langComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation( javax.swing.WindowConstants.DISPOSE_ON_CLOSE );
        setName( "Form" ); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle( "org/jbookshelf/gui/Bundle" ); // NOI18N
        restoreButton.setText( bundle.getString( "SettingsDialog.restoreButton.text" ) ); // NOI18N
        restoreButton.setName( "restoreButton" ); // NOI18N
        restoreButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                restoreButtonActionPerformed( evt );
            }
        } );

        cancelButton.setText( bundle.getString( "SettingsDialog.cancelButton.text" ) ); // NOI18N
        cancelButton.setName( "cancelButton" ); // NOI18N
        cancelButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                cancelButtonActionPerformed( evt );
            }
        } );

        okButton.setText( bundle.getString( "SettingsDialog.okButton.text" ) ); // NOI18N
        okButton.setName( "okButton" ); // NOI18N
        okButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                okButtonActionPerformed( evt );
            }
        } );

        saveButton.setText( bundle.getString( "SettingsDialog.saveButton.text" ) ); // NOI18N
        saveButton.setName( "saveButton" ); // NOI18N
        saveButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                saveButtonActionPerformed( evt );
            }
        } );

        jLabel1.setFont( new java.awt.Font( "Dialog", 1, 18 ) );
        jLabel1.setText( bundle.getString( "SettingsDialog.jLabel1.text" ) ); // NOI18N
        jLabel1.setName( "jLabel1" ); // NOI18N

        jSeparator1.setName( "jSeparator1" ); // NOI18N

        jLabel2.setText( bundle.getString( "SettingsDialog.jLabel2.text" ) ); // NOI18N
        jLabel2.setName( "jLabel2" ); // NOI18N

        jLabel3.setText( bundle.getString( "SettingsDialog.jLabel3.text" ) ); // NOI18N
        jLabel3.setName( "jLabel3" ); // NOI18N

        jLabel4.setText( bundle.getString( "SettingsDialog.jLabel4.text" ) ); // NOI18N
        jLabel4.setName( "jLabel4" ); // NOI18N

        jLabel5.setText( bundle.getString( "SettingsDialog.jLabel5.text" ) ); // NOI18N
        jLabel5.setName( "jLabel5" ); // NOI18N

        jLabel6.setText( bundle.getString( "SettingsDialog.jLabel6.text" ) ); // NOI18N
        jLabel6.setName( "jLabel6" ); // NOI18N

        importTextField.setName( "importTextField" ); // NOI18N

        jbsTextField.setName( "jbsTextField" ); // NOI18N

        chooseJBSFolderButton.setText( bundle.getString( "SettingsDialog.chooseJBSFolderButton.text" ) ); // NOI18N
        chooseJBSFolderButton.setName( "chooseJBSFolderButton" ); // NOI18N
        chooseJBSFolderButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                chooseJBSFolderButtonActionPerformed( evt );
            }
        } );

        tmpTextField.setName( "tmpTextField" ); // NOI18N

        chooseTempFolderButton.setText( bundle.getString( "SettingsDialog.chooseTempFolderButton.text" ) ); // NOI18N
        chooseTempFolderButton.setName( "chooseTempFolderButton" ); // NOI18N
        chooseTempFolderButton.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                chooseTempFolderButtonActionPerformed( evt );
            }
        } );

        lafComboBox.setModel( new javax.swing.DefaultComboBoxModel( Resourses.LAF_NAMES ) );
        lafComboBox.setName( "lafComboBox" ); // NOI18N
        lafComboBox.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                lafComboBoxActionPerformed( evt );
            }
        } );

        langComboBox.setModel( new javax.swing.DefaultComboBoxModel( new String[] { "Russian", "English" } ) );
        langComboBox.setName( "langComboBox" ); // NOI18N
        langComboBox.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                langComboBoxActionPerformed( evt );
            }
        } );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
        getContentPane().setLayout( layout );
        layout
            .setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
                layout.createSequentialGroup().addComponent( jLabel1 ).addContainerGap() ).addComponent( jSeparator1,
                javax.swing.GroupLayout.DEFAULT_SIZE, 695, Short.MAX_VALUE ).addGroup(
                layout.createSequentialGroup().addContainerGap().addComponent( saveButton ).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( restoreButton ).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE ).addComponent( okButton )
                    .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( cancelButton )
                    .addContainerGap() ).addGroup(
                layout.createSequentialGroup().addContainerGap()
                    .addGroup(
                        layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addComponent( jLabel6 )
                            .addComponent( jLabel5 ).addComponent( jLabel4 ).addComponent( jLabel3 ).addComponent(
                                jLabel2 ) ).addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED )
                    .addGroup(
                        layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addComponent(
                            importTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE )
                            .addGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING,
                                layout.createSequentialGroup().addGroup(
                                    layout.createParallelGroup( javax.swing.GroupLayout.Alignment.TRAILING )
                                        .addComponent( langComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 434,
                                            Short.MAX_VALUE ).addComponent( lafComboBox,
                                            javax.swing.GroupLayout.Alignment.LEADING, 0, 434, Short.MAX_VALUE )
                                        .addComponent( tmpTextField, javax.swing.GroupLayout.Alignment.LEADING,
                                            javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE ).addComponent(
                                            jbsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE ) )
                                    .addPreferredGap( javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                                        layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
                                            .addComponent( chooseTempFolderButton )
                                            .addComponent( chooseJBSFolderButton ) ) ) ).addContainerGap() ) );
        layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            javax.swing.GroupLayout.Alignment.TRAILING,
            layout.createSequentialGroup().addComponent( jLabel1 ).addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addComponent( jSeparator1,
                javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE ).addPreferredGap(
                javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel2 )
                    .addComponent( langComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18,
                18, 18 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel3 )
                    .addComponent( lafComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18,
                18, 18 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel4 )
                    .addComponent( tmpTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ).addComponent(
                        chooseTempFolderButton ) ).addGap( 18, 18, 18 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel5 )
                    .addComponent( chooseJBSFolderButton ).addComponent( jbsTextField,
                        javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18, 18, 18 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( jLabel6 )
                    .addComponent( importTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE ) ).addGap( 18,
                18, 18 ).addGroup(
                layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent( saveButton )
                    .addComponent( restoreButton ).addComponent( cancelButton ).addComponent( okButton ) )
                .addContainerGap() ) );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private JFileChooser fileChooser = new JFileChooser();

    private void chooseTempFolderButtonActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_chooseTempFolderButtonActionPerformed
        fileChooser.setCurrentDirectory( new File( settings.getProperty( TEMP_FOLDER ) ) );
        if ( fileChooser.showOpenDialog( this ) == JFileChooser.APPROVE_OPTION )
        {
            tmpTextField.setText( fileChooser.getSelectedFile().getAbsolutePath() );
        }
    }// GEN-LAST:event_chooseTempFolderButtonActionPerformed

    private void chooseJBSFolderButtonActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_chooseJBSFolderButtonActionPerformed
        fileChooser.setCurrentDirectory( new File( settings.getProperty( JBS_FOLDER ) ) );
        if ( fileChooser.showOpenDialog( this ) == JFileChooser.APPROVE_OPTION )
        {
            jbsTextField.setText( fileChooser.getSelectedFile().getAbsolutePath() );
        }
    }// GEN-LAST:event_chooseJBSFolderButtonActionPerformed

    private void okButtonActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_okButtonActionPerformed
        readSettingValues();
        settings.save( settings.getSettingsFile().getAbsolutePath(), true );
        dispose();
    }// GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }// GEN-LAST:event_cancelButtonActionPerformed

    private void restoreButtonActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_restoreButtonActionPerformed
        settings.loadDefaults();
        arrangeSettingValues();
    }// GEN-LAST:event_restoreButtonActionPerformed

    private void saveButtonActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_saveButtonActionPerformed
        readSettingValues();
        settings.saveAsDefaults();
    }// GEN-LAST:event_saveButtonActionPerformed

    private void lafComboBoxActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_lafComboBoxActionPerformed
        try
        {
            String lafName = lafComboBox.getSelectedItem().toString();
            settings.setProperty( JBookShelfSettings.LAF, lafName );
            UIManager.setLookAndFeel( Resourses.getLAFClassName( lafName ) );
            SwingUtilities.updateComponentTreeUI( this );
            pack();
            SwingUtilities.updateComponentTreeUI( getParent() );
            ((Window) getParent()).pack();
        }
        catch ( Exception ex )
        {
            throw new Error( ex );
        }
    }// GEN-LAST:event_lafComboBoxActionPerformed

    private void langComboBoxActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_langComboBoxActionPerformed
        String language = langComboBox.getSelectedItem().toString();
        settings.setProperty( JBookShelfSettings.LANGUAGE, language );
        Resourses.switchLanguage( language );
        ResourceBundle bundle;
        if ( language.equals( "Russian" ) )
        {
            bundle = ResourceBundle.getBundle( "org/jbookshelf/gui/Bundle", new Locale( "ru", "RU" ) );
        }
        else
        {
            bundle = ResourceBundle.getBundle( "org/jbookshelf/gui/Bundle", new Locale( "en", "US" ) );
        }

        for ( Component component : components )
        {
            String text = bundle.getString( "SettingsDialog." + component.getName() + ".text" );
            if ( component instanceof JButton )
            {
                ((JButton) component).setText( text );
            }
            else if ( component instanceof JLabel )
            {
                ((JLabel) component).setText( text );
            }
        }
    }// GEN-LAST:event_langComboBoxActionPerformed

    /**
     * stores component names to iterate while changing locale
     */
    private List<Component> components = new ArrayList<Component>();

    /**
     * register components to be localized
     */
    private void registerComponents()
    {
        components.add( restoreButton );
        components.add( chooseJBSFolderButton );
        components.add( cancelButton );
        components.add( okButton );
        components.add( saveButton );
        components.add( chooseTempFolderButton );

        components.add( jLabel1 );
        components.add( jLabel2 );
        components.add( jLabel3 );
        components.add( jLabel4 );
        components.add( jLabel5 );
        components.add( jLabel6 );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton    cancelButton;
    private javax.swing.JButton    chooseJBSFolderButton;
    private javax.swing.JButton    chooseTempFolderButton;
    private javax.swing.JTextField importTextField;
    private javax.swing.JLabel     jLabel1;
    private javax.swing.JLabel     jLabel2;
    private javax.swing.JLabel     jLabel3;
    private javax.swing.JLabel     jLabel4;
    private javax.swing.JLabel     jLabel5;
    private javax.swing.JLabel     jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jbsTextField;
    private javax.swing.JComboBox  lafComboBox;
    private javax.swing.JComboBox  langComboBox;
    private javax.swing.JButton    okButton;
    private javax.swing.JButton    restoreButton;
    private javax.swing.JButton    saveButton;
    private javax.swing.JTextField tmpTextField;
    // End of variables declaration//GEN-END:variables
}
