
    alter table Author_Book 
        drop constraint FK_BOOK_AUTHOR;

    alter table Author_Book 
        drop constraint FK_AUTHOR_BOOK;

    alter table Category 
        drop constraint FK_PARENT_CATEGORY;

    alter table Category_Book 
        drop constraint FK_BOOK_CATEGORY;

    alter table Category_Book 
        drop constraint FK_CATEGORY_BOOK;

    alter table Note 
        drop constraint FK_NOTE_BOOK;

    alter table PHYSICAL_BOOK 
        drop constraint FK_PHYSICAL_BOOK;

    alter table RELATED_BOOKS 
        drop constraint FK_MAIN_BOOK;

    alter table RELATED_BOOKS 
        drop constraint FK_RELATED_BOOK;

    drop table Author if exists;

    drop table Author_Book if exists;

    drop table Book if exists;

    drop table Category if exists;

    drop table Category_Book if exists;

    drop table Note if exists;

    drop table PHYSICAL_BOOK if exists;

    drop table RELATED_BOOKS if exists;

    create table Author (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table Author_Book (
        authors_id bigint not null,
        books_id bigint not null,
        primary key (authors_id, books_id)
    );

    create table Book (
        id bigint generated by default as identity,
        name varchar(255) not null,
        read float,
        primary key (id)
    );

    create table Category (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        parent_id bigint,
        primary key (id)
    );

    create table Category_Book (
        categories_id bigint not null,
        books_id bigint not null,
        primary key (categories_id, books_id)
    );

    create table Note (
        id bigint generated by default as identity,
        changeDate timestamp not null,
        citation varchar(32767),
        content varchar(32767),
        pos float,
        title varchar(255) not null,
        BOOK_ID bigint not null,
        primary key (id)
    );

    create table PHYSICAL_BOOK (
        id bigint generated by default as identity,
        charsetName varchar(255),
        fileName varchar(255) not null,
        unpackedFileName varchar(255),
        viewer varchar(255),
        book_id bigint not null,
        primary key (id),
        unique (book_id)
    );

    create table RELATED_BOOKS (
        Book_id bigint not null,
        relatedBooks_id bigint not null,
        primary key (Book_id, relatedBooks_id)
    );

    create index author_name_ind on Author (name);

    alter table Author_Book 
        add constraint FK_BOOK_AUTHOR 
        foreign key (authors_id) 
        references Author;

    alter table Author_Book 
        add constraint FK_AUTHOR_BOOK 
        foreign key (books_id) 
        references Book;

    create index book_name_ind on Book (name);

    create index category_name_ind on Category (name);

    alter table Category 
        add constraint FK_PARENT_CATEGORY 
        foreign key (parent_id) 
        references Category;

    alter table Category_Book 
        add constraint FK_BOOK_CATEGORY 
        foreign key (categories_id) 
        references Category;

    alter table Category_Book 
        add constraint FK_CATEGORY_BOOK 
        foreign key (books_id) 
        references Book;

    alter table Note 
        add constraint FK_NOTE_BOOK 
        foreign key (BOOK_ID) 
        references Book;

    alter table PHYSICAL_BOOK 
        add constraint FK_PHYSICAL_BOOK 
        foreign key (book_id) 
        references Book;

    alter table RELATED_BOOKS 
        add constraint FK_MAIN_BOOK 
        foreign key (Book_id) 
        references Book;

    alter table RELATED_BOOKS 
        add constraint FK_RELATED_BOOK 
        foreign key (relatedBooks_id) 
        references Book;
