/*
 * AboutDialog.java Created on 23 Ноябрь 2008 г., 19:16
 */

package org.jbookshelf.gui;

/**
 * @author eav
 */
public class AboutDialog
    extends javax.swing.JDialog
{

    /** Creates new form AboutDialog */
    public AboutDialog(
        java.awt.Frame parent,
        boolean modal )
    {
        super( parent, modal );
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        authorLabel = new javax.swing.JLabel();
        authorValueLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        versionValueLabel = new javax.swing.JLabel();
        licenseLabel = new javax.swing.JLabel();
        licenseValueLabel = new javax.swing.JLabel();

        setDefaultCloseOperation( javax.swing.WindowConstants.DISPOSE_ON_CLOSE );

        jPanel1.setLayout( new java.awt.BorderLayout() );

        header.setFont( new java.awt.Font( "Dialog", 1, 18 ) ); // NOI18N
        header.setHorizontalAlignment( javax.swing.SwingConstants.CENTER );
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle( "org/jbookshelf/gui/Bundle" ); // NOI18N
        header.setText( bundle.getString( "AboutDialog.header.text" ) ); // NOI18N
        jPanel1.add( header, java.awt.BorderLayout.PAGE_START );

        jButton1.setText( bundle.getString( "AboutDialog.jButton1.text" ) ); // NOI18N
        jButton1.addActionListener( new java.awt.event.ActionListener()
        {
            public void actionPerformed(
                java.awt.event.ActionEvent evt )
            {
                jButton1ActionPerformed( evt );
            }
        } );
        jPanel1.add( jButton1, java.awt.BorderLayout.PAGE_END );

        authorLabel.setText( bundle.getString( "AboutDialog.authorLabel.text" ) ); // NOI18N

        authorValueLabel.setText( bundle.getString( "AboutDialog.authorValueLabel.text" ) ); // NOI18N

        versionLabel.setText( bundle.getString( "AboutDialog.versionLabel.text" ) ); // NOI18N

        versionValueLabel.setText( bundle.getString( "AboutDialog.versionValueLabel.text" ) ); // NOI18N

        licenseLabel.setText( bundle.getString( "AboutDialog.licenseLabel.text" ) ); // NOI18N

        licenseValueLabel.setText( bundle.getString( "AboutDialog.licenseValueLabel.text" ) ); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout( jPanel2 );
        jPanel2.setLayout( jPanel2Layout );
        jPanel2Layout.setHorizontalGroup( jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
            .addGroup(
                jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(
                    jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
                        jPanel2Layout.createSequentialGroup().addComponent( authorLabel ).addGap( 18, 18, 18 )
                            .addComponent( authorValueLabel ) ).addGroup(
                        jPanel2Layout.createSequentialGroup().addComponent( versionLabel ).addGap( 18, 18, 18 )
                            .addComponent( versionValueLabel ) ).addGroup(
                        jPanel2Layout.createSequentialGroup().addComponent( licenseLabel ).addGap( 18, 18, 18 )
                            .addComponent( licenseValueLabel ) ) ).addContainerGap(
                    javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE ) ) );
        jPanel2Layout.setVerticalGroup( jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING )
            .addGroup(
                jPanel2Layout.createSequentialGroup().addContainerGap().addGroup(
                    jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent(
                        authorLabel ).addComponent( authorValueLabel ) ).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                    jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent(
                        versionLabel ).addComponent( versionValueLabel ) ).addPreferredGap(
                    javax.swing.LayoutStyle.ComponentPlacement.RELATED ).addGroup(
                    jPanel2Layout.createParallelGroup( javax.swing.GroupLayout.Alignment.BASELINE ).addComponent(
                        licenseLabel ).addComponent( licenseValueLabel ) ).addContainerGap( 28, Short.MAX_VALUE ) ) );

        jPanel1.add( jPanel2, java.awt.BorderLayout.CENTER );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout( getContentPane() );
        getContentPane().setLayout( layout );
        layout.setHorizontalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup().addContainerGap().addComponent( jPanel1,
                javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE ).addContainerGap() ) );
        layout.setVerticalGroup( layout.createParallelGroup( javax.swing.GroupLayout.Alignment.LEADING ).addGroup(
            layout.createSequentialGroup().addContainerGap().addComponent( jPanel1,
                javax.swing.GroupLayout.PREFERRED_SIZE, 144, Short.MAX_VALUE ).addContainerGap() ) );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(
        @SuppressWarnings( "unused" ) java.awt.event.ActionEvent evt )
    {// GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }// GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel  authorLabel;
    private javax.swing.JLabel  authorValueLabel;
    private javax.swing.JLabel  header;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel  jPanel1;
    private javax.swing.JPanel  jPanel2;
    private javax.swing.JLabel  licenseLabel;
    private javax.swing.JLabel  licenseValueLabel;
    private javax.swing.JLabel  versionLabel;
    private javax.swing.JLabel  versionValueLabel;
    // End of variables declaration//GEN-END:variables

}
