package org.jbookshelf.model.db.cayenne.auto;

import java.util.Set;

import org.apache.cayenne.CayenneDataObject;
import org.jbookshelf.model.db.cayenne.Book;

/**
 * Class _Author was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Author extends CayenneDataObject {

    public static final String NAME_PROPERTY = "name";
    public static final String BOOKS_PROPERTY = "books";

    public static final String ID_PK_COLUMN = "ID";

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToBooks(Book obj) {
        addToManyTarget("books", obj, true);
    }
    public void removeFromBooks(Book obj) {
        removeToManyTarget("books", obj, true);
    }
    @SuppressWarnings("unchecked")
    public Set<Book> getBooks() {
        return (Set<Book>)readProperty("books");
    }


}
